# Módulo 6.1 — Solución: Ficha de Estudiantes

Resolución paso a paso del **Caso Práctico** de la clase 6.1 (`Introducción a Pandas - Series y DataFrames`).

Construimos, desde cero, un DataFrame de estudiantes y lo exploramos con los métodos básicos de Pandas.

## Paso 1: Crear el diccionario y el DataFrame

Un diccionario con 6 estudiantes: `nombre`, `carrera`, `semestre`, `nota` y `asistencia`. Cada clave del diccionario se convierte en una columna.

In [1]:
import pandas as pd

datos = {
    'nombre':     ['Ana', 'Bruno', 'Camila', 'Diego', 'Elena', 'Fabián'],
    'carrera':    ['Ingeniería', 'Medicina', 'Derecho', 'Administración', 'Arquitectura', 'Psicología'],
    'semestre':   [4, 2, 6, 3, 5, 1],
    'nota':       [9.03, 8.24, 7.51, 8.77, 6.88, 9.31],
    'asistencia': [95, 92, 78, 91, 65, 97]
}

mis_estudiantes = pd.DataFrame(datos)
mis_estudiantes

   nombre         carrera  semestre  nota  asistencia
0     Ana      Ingeniería         4  9.03          95
1   Bruno        Medicina         2  8.24          92
2  Camila         Derecho         6  7.51          78
3   Diego  Administración         3  8.77          91
4   Elena    Arquitectura         5  6.88          65
5  Fabián      Psicología         1  9.31          97

## Paso 2: Explorar con `.head()`, `.info()` y `.describe()`

Antes de hacer cualquier cosa con el DataFrame, conviene explorarlo primero.

In [2]:
mis_estudiantes.head(3)

   nombre     carrera  semestre  nota  asistencia
0     Ana  Ingeniería         4  9.03          95
1   Bruno    Medicina         2  8.24          92
2  Camila     Derecho         6  7.51          78

In [3]:
mis_estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      6 non-null      object
 1   carrera     6 non-null      object
 2   semestre    6 non-null      int64
 3   nota        6 non-null      float64
 4   asistencia  6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 368.0+ bytes

In [4]:
mis_estudiantes.describe()

       semestre      nota  asistencia
count  6.000000  6.000000    6.000000
mean   3.500000  8.290000   86.333333
std    1.870829  0.939936   12.388166
min    1.000000  6.880000   65.000000
25%    2.250000  7.692500   81.250000
50%    3.500000  8.505000   91.500000
75%    4.750000  8.965000   94.250000
max    6.000000  9.310000   97.000000

`.info()` confirma que no hay nulos (las 6 columnas tienen 6 valores no nulos) y `.describe()` resume las columnas numéricas: promedio, mínimo, máximo, etc.

## Paso 3: Seleccionar solo `nombre` y `nota`

Usamos una lista de nombres de columna para quedarnos con un DataFrame más pequeño.

In [5]:
nombre_y_nota = mis_estudiantes[['nombre', 'nota']]
nombre_y_nota

   nombre  nota
0     Ana  9.03
1   Bruno  8.24
2  Camila  7.51
3   Diego  8.77
4   Elena  6.88
5  Fabián  9.31

## Paso 4: Primera y última fila con `.loc` / `.iloc`

Como el índice es el numérico por defecto (0, 1, 2...), tanto `.loc` como `.iloc` funcionan aquí, pero por significado: `.iloc` es la forma correcta de decir "la primera" y "la última" fila **por posición**, sin importar qué etiqueta tenga el índice.

In [6]:
mis_estudiantes.iloc[0]

nombre               Ana
carrera       Ingeniería
semestre               4
nota                9.03
asistencia            95
Name: 0, dtype: object

In [7]:
mis_estudiantes.iloc[-1]

nombre            Fabián
carrera       Psicología
semestre               1
nota                9.31
asistencia            97
Name: 5, dtype: object

## Paso 5: Agregar `nota_redondeada` con `.round()`

In [8]:
mis_estudiantes['nota_redondeada'] = mis_estudiantes['nota'].round(1)
mis_estudiantes[['nombre', 'nota', 'nota_redondeada']]

   nombre  nota  nota_redondeada
0     Ana  9.03              9.0
1   Bruno  8.24              8.2
2  Camila  7.51              7.5
3   Diego  8.77              8.8
4   Elena  6.88              6.9
5  Fabián  9.31              9.3

## Paso 6: Agregar la columna booleana `beca`

`True` si `nota >= 8.5` **y** `asistencia >= 90`. Como son dos condiciones sobre columnas completas, se combinan con `&` (no con `and`), y cada condición va entre paréntesis.

In [9]:
mis_estudiantes['beca'] = (mis_estudiantes['nota'] >= 8.5) & (mis_estudiantes['asistencia'] >= 90)
mis_estudiantes[['nombre', 'nota', 'asistencia', 'beca']]

   nombre  nota  asistencia   beca
0     Ana  9.03          95   True
1   Bruno  8.24          92  False
2  Camila  7.51          78  False
3   Diego  8.77          91   True
4   Elena  6.88          65  False
5  Fabián  9.31          97   True

Ana, Diego y Fabián cumplen ambas condiciones a la vez; Bruno tiene buena asistencia pero nota menor a 8.5; Camila y Elena no cumplen ninguna.

## Paso 7: Promedio de `nota` y de `asistencia`

In [10]:
promedio_nota = mis_estudiantes['nota'].mean()
promedio_asistencia = mis_estudiantes['asistencia'].mean()

print(f'Promedio de nota: {promedio_nota:.2f}')
print(f'Promedio de asistencia: {promedio_asistencia:.2f}%')

Promedio de nota: 8.29
Promedio de asistencia: 86.33%

## Resultado final

El DataFrame completo, con todas las columnas agregadas durante el ejercicio.

In [11]:
mis_estudiantes

   nombre         carrera  semestre  nota  asistencia  nota_redondeada   beca
0     Ana      Ingeniería         4  9.03          95              9.0   True
1   Bruno        Medicina         2  8.24          92              8.2  False
2  Camila         Derecho         6  7.51          78              7.5  False
3   Diego  Administración         3  8.77          91              8.8   True
4   Elena    Arquitectura         5  6.88          65              6.9  False
5  Fabián      Psicología         1  9.31          97              9.3   True